{{- if and .Values.hfToken.value (not .Values.hfToken.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hf-csi-driver.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hf-csi-driver.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.hfToken.existingSecretKey }}: {{ .Values.hfToken.value | quote }}
{{- end }}
